# Use the official Golang image to create a build artifact.
FROM golang:1.16 as builder

# Create a directory for the application.
WORKDIR /app

# Copy the Go Modules manifests and download dependencies.
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code into the container.
COPY . .

# Compile the application.
RUN CGO_ENABLED=0 GOOS=linux go build -v -o server

# Use a Docker multi-stage build to create a lean production image.
FROM alpine:latest  
RUN apk --no-cache add ca-certificates

WORKDIR /root/

# Copy the binary to the production image from the builder stage.
COPY --from=builder /app/server .

# Run the binary.
CMD ["./server"]
