# Use the official Nginx image from Docker Hub
FROM nginx:latest

# Optional: Remove the default server definition
RUN rm /etc/nginx/conf.d/default.conf

# Optional: Copy a custom Nginx configuration file
COPY ./my-nginx.conf /etc/nginx/nginx.conf

# Copy the content of your site into the HTML directory
COPY ./public-html/ /usr/share/nginx/html/

# Expose HTTP and HTTPS ports
EXPOSE 80 443

# Start Nginx in the foreground (default command in the nginx image)
CMD ["nginx", "-g", "daemon off;"]
